"use strict";

const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..");
const cssRoot = path.join(projectRoot, "assets/css");
const entryPath = path.join(cssRoot, "style.css");
const outputPath = path.join(cssRoot, "site.bundle.css");

const imports = [
    ...fs.readFileSync(entryPath, "utf8")
        .matchAll(/@import\s+url\(["']([^"']+)["']\);/g)
].map(match => match[1].split("?")[0]);

const banner =
    "/* Generated by scripts/build-css.js. Edit the component CSS files, not this bundle. */\n";

const bundle = imports
    .map(fileName => {
        const source = fs.readFileSync(
            path.join(cssRoot, fileName),
            "utf8"
        );

        return `\n/* ${fileName} */\n${source.trim()}\n`;
    })
    .join("");

fs.writeFileSync(outputPath, `${banner}${bundle}`);

console.log(
    `Built ${path.relative(projectRoot, outputPath)} from ${imports.length} component files.`
);
